apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: node
          image: mohamedmagdy12/nodejs:latest
          ports:
            - name: app
              containerPort: 3000
